config/routes.rb
Rails.application.routes.draw do
    resources :tweets
    root'tweets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :message, presence: true
    validates :message, length: {maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
       @tweet = Tweet.all
    end
    
    def new
       @tweet = Tweet.new
    end
    
    def create
       message = params[:tweet][:message]
       tdate = Time.current
       
       @tweet = Tweet.new(message: message, tdate: tdate)
       if @tweet.save
           flash[:notice] = '[１メッセージ追加しました]'
           redirect_to tweets_path
       else
           render 'new'
       end
    end
    
    def destroy
       tweet = Tweet.find(params[:id])
       tweet.destroy
       redirect_to tweets_path
    end
    
    def edit
       @tweet = Tweet.find(params[:id]) 
    end
    
    def update
       @tweet = Tweet.find(params[:id])
       message = params[:tweet][:message]
       @tweet.update(message: message)
       
       if @tweet.save
           flash[:notice] = '[１メッセージ更新しました]'
           redirect_to tweets_path
       else
           render 'new'
       end
    end
    
    def show
       @tweet = Tweet.find(params[:id]) 
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    #def date_format(datetime)
       #time_ago_in_words(datetime) + '前' 
    #end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <div id="header">
        <%= render "header" %>
      </div>
      <div id="sidebar">
        <%= render "sidebar" %>
      </div>
      <div id="content">

        <%= yield %>

      </div>
      <div id="footer">
        <%= render "footer" %>
      </div>
    </div>
  </body>
</html>

app/views/tweets/_form.html.erb
<p class = "form">140文字以内で入力して下さい</p>

app/views/tweets/_header.html.erb
<nav>
    <ul class = "center">

        <li><a><%= link_to 'ホーム', tweets_path %></a></li>
        <li><a href = ".">ツイートと返信</a></li>
        <li><a href = ".">メディア</a></li>
        <li><a href = ".">いいね</a></li>
    </ul>
</nav>

app/views/tweets/_sidebar.html.erb
<p class = "ha-botan">
    <%= link_to '　🏠 　ホーム', tweets_path, class:"link-1" %>
</p>
<p>　 ＃　 話題を検索</p>
<p>　 🔔　 通知</p>
<p>　 ✉ 　メッセージ</p>
<p>　 □ 　ブックマーク</p>
<p>　 □ 　リスト</p>
<p>　 👤　 プロフィール</p>
<p>　 〇 　もっと見る</p>

<p class = "ao-botan">
    <%= link_to '　ツイートする', new_tweet_path, class:"link" %>
</p>

app/views/tweets/edit.html.erb
<%= render "form" %>

<%= form_for @tweet, url: {action: :update} do |f| %>
<div class = "pageBody-text">
    <p class = "text-area">
        <%= f.label :message, 'ツイート' %>
        <%= f.text_area :message %>
    </p>
    <div class = "text-btn">
        <%= f.submit '更新' %>
    </div>
</div>

<% end %>

app/views/tweets/index.html.erb
<% @tweet.each do |tweet| %>

    <div class = "pageBody">
        <nobr class = "right-space">
            <%= image_tag "パターン04.png", size: '27x27' %>
            <a class = "huto">
                &nbsp;&nbsp;&nbsp;近畿大学
            </a>
                <%= '@kinikidaigakuPR・' %>
                <%= tweet.tdate.strftime("%m月%d日") %>
            <a class = "right-link">
                <%= link_to '・・・', tweet_path(tweet.id), class:"right-link", method: :delete %>
            </a>
        </nobr>
    
        <br>
        <a class =  "right-space1">
            <%= safe_join(tweet.message.split("\n"),tag(:br)) %>
            
        </a>
        <a class = "pageBody-s">
            <%= image_tag "snow07.png" %>
            <p>
                情報学部｜近畿大学<br>
                近畿大学公式ウェブサイト。このページは、情報学部に関する情報をご覧いただけます。<br>
                🔗kindai.ac.jp
            </p>
        </a>
        <p class =  "right-space1">💭 2 　 　□ 14 　 　♡ 69  　　　　□</p>
    </div>
<% end %>

app/views/tweets/new.html.erb
<% if @tweet.errors.present? %>
    <h3 class = "pageBody-text">エラーがあります。</h3>
    <ul>
        <% @tweet.errors.full_messages.each do |msg| %>
        <li class = "pageBody-text"><%= msg %></li>
        <% end %>
    </ul>

<% end %>


<%= render "form" %>
<div class = "pageBody-text">
    <%= form_for @tweet, url: {action: :create} do |f| %>

        <p class = "text-area">
            <%= f.label :message, 'ツイート' %>
            <%= f.text_area :message %>
        </p>
        <div class = "text-btn">
            <%= f.submit '投稿' %>
        </div>
    <% end %>
</div>

app/views/tweets/show.html.erb
<p>
    <strong>メッセージ</strong>
    <br>
    <%= @tweet.message %>
</p>

<p>
    <strong>投稿日時</strong>
    <br>
    <%= @tweet.tdate.strftime("%Y年%m月%d日 %H時%M分%S秒") %>
 
</p>

<%= link_to '戻る', :back %>